/*
 * Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package main

import (
	"fmt"

	"ballerina-lang-go/cli/pkg/templates"

	"github.com/spf13/cobra"
)

var bindgenLongDesc = `Generate Ballerina bridge code for Java APIs.

Ballerina bindings could be generated for Java classes residing inside Java libraries or standard Java
classes. The Java classes will be mapped onto Ballerina classes making the developer experience of
Ballerina Java interoperability seamless.

In addition to the user-specified Java classes, partially-implemented bindings for dependent Java classes
will also be generated by the tool. By default, the bindings for each Java package will be mapped to a
separate Ballerina module.`

var bindgenExamples = []templates.Example{
	{
		Description: "Generate bindings for a Java class.",
		Commands:    []string{"bal bindgen java.util.ArrayList"},
	},
	{
		Description: "Generate bindings from a JAR file.",
		Commands:    []string{"bal bindgen -cp mylib.jar com.example.MyClass"},
	},
}

func NewBindgenCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:           "bindgen [OPTIONS] <java-class-name>...",
		Short:         "Generate Ballerina bindings for Java APIs",
		Long:          bindgenLongDesc,
		Example:       templates.FormatExamples(bindgenExamples),
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE:          runBindgen,
	}

	return cmd
}

func runBindgen(cmd *cobra.Command, args []string) error {
	err := fmt.Errorf("command 'bindgen' is not yet implemented")
	printError(err, "", false, cmd.Name())
	return err
}
